pub mod rust_codegen;

#[macro_export]
macro_rules! concat_with_spaces {
    ($lhs: expr, $rhs: expr) => {
        std::concat!($lhs, " ", $rhs, "\n") 
    };
}

#[macro_export]
macro_rules! get_docs {
    ($prefix:expr) => {
        std::concat!(
            crate::concat_with_spaces!($prefix, "Code generated by razz-compiler"),
            crate::concat_with_spaces!($prefix, std::concat!("Version: ", env!("CARGO_PKG_VERSION"))),
            crate::concat_with_spaces!($prefix, "Compiler made by Jason Phan @ https://github.com/sudo-jp"),
            crate::concat_with_spaces!($prefix, "Compiler Source Code @ https://github.com/sudo-JP/Razz/tree/main/razz-compiler")
        )
    };
}
