pub mod rust_codegen;
pub(crate) mod rust_preprocess;

#[macro_export]
macro_rules! cat {
    ($lhs: expr, $rhs: expr) => {
        std::concat!($lhs, " ", $rhs, "\n") 
    };
}

#[macro_export]
macro_rules! get_docs {
    ($prefix:expr) => {
        {
            use crate::cat;
            use std::concat;
            std::concat!(
                cat!($prefix, "Code generated by razz-compiler"),
                cat!($prefix, concat!("Version: ", env!("CARGO_PKG_VERSION"))),
                cat!($prefix, "Compiler made by Jason Phan @ https://github.com/sudo-jp"),
                cat!($prefix, "Compiler Source Code @ https://github.com/sudo-JP/Razz/")
            )
        }
    };
}
